name: Deploy

on:
  push:
    branches: [main]

jobs:
  
  
  # Prod: Terraform Steps
  terraform-prod:
    runs-on: ubuntu-18.04
    steps:
      # Checkout
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: "Prod: Prepare Terraform Files"
        run: |
          echo 'hello' > me.txt
        env:
          AWS_ACCESS_KEY_ID: AKIAXFBZVRW352IRKGET
          AWS_SECRET_ACCESS_KEY: 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
      - name: "Prod: Terraform Init"
        run: cd terraform/ && terraform init -backend-config="access_key=AKIAXFBZVRW352IRKGET" -backend-config="secret_key=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"
        env:
          AWS_ACCESS_KEY_ID: AKIAXFBZVRW352IRKGET
          AWS_SECRET_ACCESS_KEY: 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
      - name: "Prod: Terraform Apply"
        run: cd terraform/ && terraform apply -no-color -auto-approve
        env:
          AWS_ACCESS_KEY_ID: AKIAXFBZVRW352IRKGET
          AWS_SECRET_ACCESS_KEY: 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



  # Prod: Serverless Steps
  serverless-prod:
    needs: terraform-prod
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: .
    steps:
      # Checkout
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: "Prod: Install Serverless"
        run: |
          sudo npm install -g serverless
          sudo npm install --save-dev serverless-stack-termination-protection
          sudo sls plugin install -n serverless-python-requirements
          sudo npm i serverless-plugin-aws-alerts
          sudo npm install serverless-plugin-resource-tagging
          sudo npm install serverless-offline --save
          sudo serverless config credentials --stage staging --provider aws --key AKIAXFBZVRW352IRKGET --secret 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
      - name: "Prod: Prepare Serverless Files"
        run: |
          BUCKET_ENV=prod
          APP_STACK_NAME=test
          APP_SERVICE_NAME=test

          sudo sed -i 's|\$\$bucket_env\$\$|'"$BUCKET_ENV"'|g' serverless.yml
          sudo sed -i 's|\$\$pr_env\$\$|'"$BUCKET_ENV"'|g' serverless.yml
          sudo sed -i 's|\$\$stackName\$\$|'"$APP_STACK_NAME"'|g' serverless.yml
          sudo sed -i 's|\$\$serviceName\$\$|'"$APP_SERVICE_NAME"'|g' serverless.yml

          LOG_GROUP=prod
          sudo sed -i 's|\$\$logGroup\$\$|'"$LOG_GROUP"'|g' serverless.yml
        env:
          AWS_ACCESS_KEY_ID: AKIAXFBZVRW352IRKGET
          AWS_SECRET_ACCESS_KEY: 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
      - name: "Prod: Serverless Deploy"
        run: |
          sudo pip install pipenv==2018.11.26
          sudo sls deploy --stage prod
        env:
          AWS_ACCESS_KEY_ID: AKIAXFBZVRW352IRKGET
          AWS_SECRET_ACCESS_KEY: 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
